### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by tiruoQing** [CalebChen768/NEU-Ipgw-auto-login#1]
acid: 15
Traceback (most recent call last):
  File "/home/tiruo/ipgw_neu/neu_i/login.py", line 113, in <module>
    main()
  File "/home/tiruo/ipgw_neu/neu_i/login.py", line 109, in main
    result, message = _login.login()
  File "/home/tiruo/ipgw_neu/neu_i/login.py", line 100, in login
    result, message = self.login_with_acid(acid)
  File "/home/tiruo/ipgw_neu/neu_i/login.py", line 72, in login_with_acid
    half = text[text.index(target) + len(target):]
ValueError: substring not found

**Comment by CalebChen768** [comment]
登录流程出现更新
登录脚本已经适配，麻烦帮忙验证下 @tiruoQing
